In [4]:
import numpy as np

In [6]:
my_arr=np.arange(1000000)

In [17]:
my_arr

array([         0,       1024,       2048, ..., 1023996928, 1023997952,
       1023998976])

In [18]:
my_list=list(range(1000000))

In [19]:
%time for _ in range(10): my_arr2=my_arr*2

Wall time: 38 ms


In [21]:
%time for _ in range(10): my_list2=[x*2 for x in my_list]

Wall time: 1.4 s


In [25]:
#语句需要紧跟在： 之后，不能换行

In [26]:
data=np.random.randn(2,3)

In [27]:
data

array([[-0.33432885, -1.26856006,  1.81648825],
       [-0.77630865,  1.04019347, -0.12274604]])

In [28]:
data*10

array([[ -3.34328848, -12.68560057,  18.16488246],
       [ -7.76308654,  10.40193471,  -1.22746036]])

In [29]:
data+data

array([[-0.6686577 , -2.53712011,  3.63297649],
       [-1.55261731,  2.08038694, -0.24549207]])

In [31]:
data.shape

(2, 3)

In [32]:
data.dtype

dtype('float64')

In [33]:
data1=[6,7.5,8,9]

In [36]:
arr1=np.array(data1)

In [38]:
arr1

array([6. , 7.5, 8. , 9. ])

In [39]:
data2=[[1,2,5.2],[2,5,4.2]]
arr2=np.array(data2)

In [40]:
arr2

array([[1. , 2. , 5.2],
       [2. , 5. , 4.2]])

In [41]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [42]:
np.empty((3,2,3))

array([[[6.23042070e-307, 7.56587584e-307, 1.37961302e-306],
        [6.23053614e-307, 6.23053954e-307, 9.34609790e-307]],

       [[8.45593934e-307, 9.34600963e-307, 1.42418987e-306],
        [8.90100844e-307, 1.69121367e-306, 8.90100844e-307]],

       [[1.69121367e-306, 8.90100844e-307, 6.89812281e-307],
        [1.78021663e-306, 1.42410974e-306, 8.34402697e-308]]])

In [43]:
arr2.dtype


dtype('float64')

In [44]:
arr=np.array([1,4,5])

In [45]:
float_arr=arr.astype(np.float64)

In [46]:
float_arr

array([1., 4., 5.])

In [47]:
arr=np.array([1.2,2.5,6.7])

In [51]:
arr.astype(np.int32)

array([1, 2, 6])

In [52]:
#不是四舍五入,是简单的去除小数点后的

In [53]:
numeric=np.array(['1.25','5.87'])

In [55]:
numeric.astype(np.float32)

array([1.25, 5.87], dtype=float32)

In [56]:
#字符串数字转换为实际数字


In [57]:
arr>data2

array([[ True,  True,  True],
       [False, False,  True]])

In [58]:
data2[0:1]

[[1, 2, 5.2]]

In [59]:
tmp=data2[0:1]

In [60]:
tmp

[[1, 2, 5.2]]

In [61]:
data=[0,1,2,3,4,5,6,7,8]

In [62]:
data[0:1]

[0]

In [63]:
tmp=data[0:2]

In [64]:
#tmp 改变  data也会改变 相当于是一副视图 而不是一份copy

In [105]:
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])# 2*2*3数组

In [106]:
oldvalues=arr3d[0].copy()

In [107]:
oldvalues

array([[1, 2, 3],
       [4, 5, 6]])

In [108]:
#copy

In [109]:
arr3d[0]=58  #可以传标量或者是数组


In [110]:
arr3d

array([[[58, 58, 58],
        [58, 58, 58]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [111]:
arr3d[0]=oldvalues

In [112]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [113]:
arr3d[0][1]


array([4, 5, 6])

In [114]:
arr3d[0,1]

array([4, 5, 6])

In [115]:
#等价

In [118]:
arr3d[1:]

array([[[ 7,  8,  9],
        [10, 11, 12]]])

In [120]:
arr3d[:,:1,:2]

array([[[1, 2]],

       [[7, 8]]])

In [121]:
arr3d[:,:,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [122]:
#布尔索引!!!

In [161]:
names=np.array(['bob','ana','bob','jane'])

In [171]:
data=np.random.rand(4,3)

In [172]:
names=='bob'

array([ True, False,  True, False])

In [173]:
data

array([[0.82213185, 0.10265861, 0.79861854],
       [0.5234526 , 0.58139521, 0.63823543],
       [0.94445779, 0.30967504, 0.11386433],
       [0.23226361, 0.06531586, 0.71269388]])

In [179]:
data==0.82213185 #？？？为什么不对

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [175]:
data[names=='bob'] #布尔索引 生成的数据与切片不同，是拷贝不是视图

array([[0.82213185, 0.10265861, 0.79861854],
       [0.94445779, 0.30967504, 0.11386433]])

In [176]:
data[names=='bob',:2]

array([[0.82213185, 0.10265861],
       [0.94445779, 0.30967504]])

In [177]:
#取反

In [178]:
data[~(names=='bob')]

array([[0.5234526 , 0.58139521, 0.63823543],
       [0.23226361, 0.06531586, 0.71269388]])

In [182]:
#多重布尔值条件 布尔值数组只能使用 & |，and or 不起作用

In [184]:
data[(names=='jane')&(names=='ana')]

array([], shape=(0, 3), dtype=float64)

In [185]:
data[(names=='jane')|(names=='ana')]

array([[0.5234526 , 0.58139521, 0.63823543],
       [0.23226361, 0.06531586, 0.71269388]])

In [137]:
tmp=np.array([[3,12],[3,4]])

In [153]:
tmp==3

array([[ True, False],
       [ True, False]])

In [140]:
tmp==[3,12] ##不是按行 而是对整个数组匹配这两个值 ！！

array([[ True,  True],
       [ True, False]])

In [186]:
#4.1.6 神奇索引 | 使用整数数组进行数据索引 |生成的数据是拷贝，不是视图（切片是视图）

In [188]:
arr=np.arange(24).reshape((6,4)) #reshape 是双括号

In [189]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [190]:
arr[ [0,2,4] ]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

In [192]:
arr[  [0,2,4],[0,1,2]  ]

array([ 0,  9, 18])

In [194]:
arr[[0,2,4]][:,[0,1]] #得到的是一个矩阵块（数组的子集），先后的思想，先取出了0、2、4三行，所以后一块行的位置：全选，再选取想要的列

array([[ 0,  1],
       [ 8,  9],
       [16, 17]])

In [196]:
#4.1.7 数组转置与换轴

In [197]:
arr=np.arange(15).reshape((3,5))

In [198]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [199]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [200]:
#矩阵的内积

In [201]:
np.dot(arr.T,arr)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [202]:
arr2=np.arange(16).reshape((2,2,4))

In [203]:
arr2

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [204]:
arr2.transpose((1,0,2)) #0,1,2是shape()三个数的顺序，原本是（0，1，2)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [208]:
arr2.transpose((2,1,0)) 

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [209]:
arr2.transpose((0,2,1))

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [210]:
#swapaxes

In [1]:
#练习题

In [2]:
import numpy as np

In [7]:
print (np.__version__)

1.16.4


In [8]:
print(np.show_config())

mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/anaconda\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/anaconda\\Library\\include']
blas_opt_in

In [11]:
arr1=np.zeros(10)

In [12]:
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
arr1.size

10

In [15]:
arr1.itemsize

8

In [16]:
np.info

<function numpy.info(object=None, maxwidth=76, output=<ipykernel.iostream.OutStream object at 0x000000C200EF9898>, toplevel='numpy')>

In [17]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [19]:
arr1=np.zeros(10)

In [20]:
arr1[4]=1

In [21]:
arr1

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [25]:
arr2=np.arange(10,50)

In [26]:
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [28]:
#反转一个向量

In [29]:
arr2[::-1] #!!!!

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [31]:
arr=np.arange(9).reshape((3,3))

In [32]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [34]:
arr1=np.array([1,2,0,0,4,0])

In [36]:
np.nonzero(arr1)#!!!

(array([0, 1, 4], dtype=int64),)

In [37]:
print(np.nonzero(arr1))

(array([0, 1, 4], dtype=int64),)


In [42]:
arr=np.ones((3,3))  

In [43]:
arr


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [45]:
arr=np.eye(3)#3*3 单位矩阵!!

In [46]:
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [51]:
arr=np.random().reshape((3,3)) #!

TypeError: 'module' object is not callable

In [53]:
arr=np.random.random((3,3,3)) #!! 3*3*3随机数组

In [56]:
arr1=np.random.random((10,10))

In [57]:
print(np.max(arr1))

0.9975362728993843


In [58]:
print(np.min(arr1))

0.00857082995250591


In [59]:
arr1=np.random.random(30)

In [60]:
print(arr1.mean())# 平均值是MEAN

0.4206754889236105


In [61]:
#！！创建一个二维数组，其中边界值为1其他为0

In [62]:
arr2=np.zeros((3,3))

In [63]:
arr2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [66]:
arr2[:,[0,-1]]=1  #切片和那个？？索引的区别

In [67]:
arr2

array([[1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.]])

In [68]:
arr2.astype(np.int32)

array([[1, 0, 1],
       [1, 0, 1],
       [1, 0, 1]])

In [72]:
#边界值为1，应当是一个矩形的1

In [78]:
arr2=np.zeros((5,5))
arr2[[0,-1],:]=1

In [80]:
arr2[1:-1,[0,-1]]=1

In [81]:
arr2

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [82]:
# 以上不够简单

In [86]:
arr2=np.ones((5,5))

In [87]:
arr2[1:-1,1:-1]=0

In [88]:
arr2

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [91]:
###!!!填充边界
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z) 

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [93]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


In [94]:
##！！！
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [95]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1  ##::前是开始的行，后是步长
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
